FROM node:24
LABEL org.opencontainers.image.source="https://github.com/atinon/commerce"
WORKDIR /client
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5174"]