FROM node:24 AS builder
LABEL org.opencontainers.image.source="https://github.com/atinon/commerce"
WORKDIR /client
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM node:24-slim AS runner
WORKDIR /client
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /client/dist ./dist
EXPOSE 5174
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5174"]