FROM node:24
LABEL org.opencontainers.image.source="https://github.com/atinon/commerce"
WORKDIR /server
COPY package*.json ./
RUN npm ci
COPY prisma ./prisma
ENV DATABASE_URL="postgresql://placeholder@localhost:5432/placeholder" 
RUN npx prisma generate
EXPOSE 3000
CMD ["npm", "run", "dev"]