FROM node:24 AS builder
LABEL org.opencontainers.image.source="https://github.com/atinon/commerce"
WORKDIR /server
COPY package*.json ./
RUN npm ci
COPY . .
ENV DATABASE_URL="postgresql://placeholder@localhost:5432/placeholder"
RUN npm run prisma:generate
RUN npm run build


FROM node:24-slim AS runner
WORKDIR /server
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /server/dist ./dist
COPY --from=builder /server/prisma ./prisma
COPY --from=builder /server/src/views ./src/views
# Prisma generated client
COPY --from=builder /server/node_modules/.prisma ./node_modules/.prisma
EXPOSE 3001
CMD ["npm", "run", "start"]